eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
server.port: 9080

spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.input.consumer.application-id: payment-service


spring.cloud.stream.bindings.input.destination: payment_topic
spring.cloud.stream.bindings.output.destination: payment_status_topic
spring.cloud.stream.bindings.payment.destination: payment_status_topic

#spring.cloud.stream.kafka.binder.brokers: 3.218.212.33
#spring.cloud.stream.kafka.binder.defaultBrokerPort: 9092
            
            